Vagrant::configure("2") do |config|

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "manifests"
		puppet.manifest_file  = "default.pp"
		puppet.module_path = "modules"
	end

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

    config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
    end

    # Forward guest port 80 to host port 8810 and name mapping
    config.vm.network :forwarded_port, guest: 80, host: 8812
    config.vm.network "private_network", ip: "192.168.50.12"

    config.vm.synced_folder ".", "/vagrant", nfs: true, nfs_version: "3", nfs_udp: true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :machine

        config.cache.synced_folder_opts = {
          type: :nfs,
          mount_options: ['rw', 'vers=3', 'udp']
        }
    end
end