Vagrant.configure("2") do |config|

  # Upgrage puppet.
  # config.vm.provision :shell, :path => "scripts/bootstrap_puppet.sh"

  # Enable the Puppet provisioner, with will look in manifests
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = ""
    puppet.manifest_file = "manifests/default.pp"
    puppet.module_path = "modules"
  end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  # Forward guest port 80 to host port 8810 and name mapping
  config.vm.network :forwarded_port, guest: 80, host: 8810

  config.vm.network "private_network", ip: "192.168.50.10"

  # config.vm.synced_folder "webroot/", "/vagrant/webroot/", :owner => "www-data"
  # If mount hangs install nfs-common and nfs-kernel-server, also the command may help: sudo rm -f /etc/exports
  config.vm.synced_folder ".", "/vagrant", nfs: true, nfs_version: "3", nfs_udp: true
  config.vm.synced_folder "webroot", "/vagrant/webroot", nfs: true, nfs_udp: true

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    # Or :machine to save in .vagrant/machines/<machine-name>/cache
    config.cache.scope = :box

    # OPTIONAL: If you are using VirtualBox, you might want to use that to enable
    # NFS for shared folders. This is also very useful for vagrant-libvirt if you
    # want bi-directional sync
    config.cache.synced_folder_opts = {
      type: :nfs,
      # The nolock option can be useful for an NFSv3 client that wants to avoid the
      # NLM sideband protocol. Without this option, apt-get might hang if it tries
      # to lock files needed for /var/cache/* operations. All of this can be avoided
      # by using NFSv4 everywhere. Please note that the tcp option is not the default.
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      # mount_options: ['rw', 'vers=4', 'udp']
    }
    # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end

end
