Vagrant.configure("2") do |config|

  # Enable the Puppet provisioner, with will look in manifests
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = ""
    puppet.manifest_file = "manifests/default.pp"
    puppet.module_path = "modules"
  end

  # Moved to module.
  # config.vm.provision :shell, :path => "scripts/bootstrap-elasticsearch.sh"

  config.vm.box = "dosbarras/raring32-lamp54"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8820
  config.vm.network "private_network", ip: "192.168.50.20"

  # NFS is too slow for SugarCRM. Use RSYNC instead.
  # If mount hangs install nfs-common and nfs-kernel-server, also the command may help: sudo rm -f /etc/exports
  config.vm.synced_folder ".", "/vagrant", nfs: true, nfs_version: "4", nfs_udp: true

  # Do not forget to run "vagrant rsync-auto". Currently (v1.6) rsync is one-way!
  # config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true,
  #  rsync__exclude: ["webroot/ult/.git/", "webroot/ult/sugarcrm/cache/*", "webroot/ult/sugarcrm/upload/*"]

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine

    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=4', 'udp']
    }
  end

end
