Vagrant.configure("2") do |config|
  config.vm.box = "phpdevbox"

  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  config.vm.network :private_network, ip: "192.168.50.12"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # nginx
  config.vm.network :forwarded_port, guest: 80, host: 8812
  # mysql
  #config.vm.network :forwarded_port, guest: 3306, host: 3306

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.options = ['--verbose']
  end

  config.vm.synced_folder ".", "/vagrant", nfs: true, nfs_udp: true

  # allow symlinks in vm
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box

    config.cache.synced_folder_opts = {
      type: :nfs
    }
  end

end